remote_theme: "mmistakes/jekyll-theme-basically-basic"
title: ask an azure architect slack

description: ask an azure architect slack
show_downloads: false
github_username: jpda
twitter_username: AzureAndChill
author:
  name: John Patrick Dandison
  twitter: AzureAndChill
  picture: /assets/images/johndoe.png